export const CountryFlagByName = {
    "Afghanistan": "🇦🇫",
    "Åland Islands": "🇦🇽",
    "Albania": "🇦🇱",
    "Algeria": "🇩🇿",
    "American Samoa": "🇦🇸",
    "Andorra": "🇦🇩",
    "Angola": "🇦🇴",
    "Anguilla": "🇦🇮",
    "Antarctica": "🇦🇶",
    "Antigua and Barbuda": "🇦🇬",
    "Argentina": "🇦🇷",
    "Armenia": "🇦🇲",
    "Aruba": "🇦🇼",
    "Australia": "🇦🇺",
    "Austria": "🇦🇹",
    "Azerbaijan": "🇦🇿",
    "Bahamas": "🇧🇸",
    "Bahrain": "🇧🇭",
    "Bangladesh": "🇧🇩",
    "Barbados": "🇧🇧",
    "Belarus": "🇧🇾",
    "Belgium": "🇧🇪",
    "Belize": "🇧🇿",
    "Benin": "🇧🇯",
    "Bermuda": "🇧🇲",
    "Bhutan": "🇧🇹",
    "Bolivia, Plurinational State of bolivia": "🇧🇴",
    "Bosnia and Herzegovina": "🇧🇦",
    "Botswana": "🇧🇼",
    "Bouvet Island": "🇧🇻",
    "Brazil": "🇧🇷",
    "British Indian Ocean Territory": "🇮🇴",
    "Brunei Darussalam": "🇧🇳",
    "Bulgaria": "🇧🇬",
    "Burkina Faso": "🇧🇫",
    "Burundi": "🇧🇮",
    "Cambodia": "🇰🇭",
    "Cameroon": "🇨🇲",
    "Canada": "🇨🇦",
    "Cape Verde": "🇨🇻",
    "Cayman Islands": "🇰🇾",
    "Central African Republic": "🇨🇫",
    "Chad": "🇹🇩",
    "Chile": "🇨🇱",
    "China": "🇨🇳",
    "Christmas Island": "🇨🇽",
    "Cocos (Keeling) Islands": "🇨🇨",
    "Colombia": "🇨🇴",
    "Comoros": "🇰🇲",
    "Congo": "🇨🇬",
    "Congo, The Democratic Republic of the Congo": "🇨🇩",
    "Cook Islands": "🇨🇰",
    "Costa Rica": "🇨🇷",
    "Cote d'Ivoire": "🇨🇮",
    "Croatia": "🇭🇷",
    "Cuba": "🇨🇺",
    "Cyprus": "🇨🇾",
    "Czech Republic": "🇨🇿",
    "Denmark": "🇩🇰",
    "Djibouti": "🇩🇯",
    "Dominica": "🇩🇲",
    "Dominican Republic": "🇩🇴",
    "Ecuador": "🇪🇨",
    "Egypt": "🇪🇬",
    "El Salvador": "🇸🇻",
    "Equatorial Guinea": "🇬🇶",
    "Eritrea": "🇪🇷",
    "Estonia": "🇪🇪",
    "Ethiopia": "🇪🇹",
    "Falkland Islands (Malvinas)": "🇫🇰",
    "Faroe Islands": "🇫🇴",
    "Fiji": "🇫🇯",
    "Finland": "🇫🇮",
    "France": "🇫🇷",
    "French Guiana": "🇬🇫",
    "French Polynesia": "🇵🇫",
    "French Southern Territories": "🇹🇫",
    "Gabon": "🇬🇦",
    "Gambia": "🇬🇲",
    "Georgia": "🇬🇪",
    "Germany": "🇩🇪",
    "Ghana": "🇬🇭",
    "Gibraltar": "🇬🇮",
    "Greece": "🇬🇷",
    "Greenland": "🇬🇱",
    "Grenada": "🇬🇩",
    "Guadeloupe": "🇬🇵",
    "Guam": "🇬🇺",
    "Guatemala": "🇬🇹",
    "Guernsey": "🇬🇬",
    "Guinea": "🇬🇳",
    "Guinea-Bissau": "🇬🇼",
    "Guyana": "🇬🇾",
    "Haiti": "🇭🇹",
    "Heard Island and Mcdonald Islands": "🇭🇲",
    "Holy See (Vatican City State)": "🇻🇦",
    "Honduras": "🇭🇳",
    "Hong Kong": "🇭🇰",
    "Hungary": "🇭🇺",
    "Iceland": "🇮🇸",
    "India": "🇮🇳",
    "Indonesia": "🇮🇩",
    "Iran, Islamic Republic of Persian Gulf": "🇮🇷",
    "Iraq": "🇮🇶",
    "Ireland": "🇮🇪",
    "Isle of Man": "🇮🇲",
    "Israel": "🇮🇱",
    "Italy": "🇮🇹",
    "Jamaica": "🇯🇲",
    "Japan": "🇯🇵",
    "Jersey": "🇯🇪",
    "Jordan": "🇯🇴",
    "Kazakhstan": "🇰🇿",
    "Kenya": "🇰🇪",
    "Kiribati": "🇰🇮",
    "Korea, Democratic People's Republic of Korea": "🇰🇵",
    "Korea, Republic of South Korea": "🇰🇷",
    "Kosovo": "🇽🇰",
    "Kuwait": "🇰🇼",
    "Kyrgyzstan": "🇰🇬",
    "Lao People's Democratic Republic": "🇱🇦",
    "Latvia": "🇱🇻",
    "Lebanon": "🇱🇧",
    "Lesotho": "🇱🇸",
    "Liberia": "🇱🇷",
    "Libyan Arab Jamahiriya": "🇱🇾",
    "Liechtenstein": "🇱🇮",
    "Lithuania": "🇱🇹",
    "Luxembourg": "🇱🇺",
    "Macao": "🇲🇴",
    "North Macedonia": "🇲🇰",
    "Madagascar": "🇲🇬",
    "Malawi": "🇲🇼",
    "Malaysia": "🇲🇾",
    "Maldives": "🇲🇻",
    "Mali": "🇲🇱",
    "Malta": "🇲🇹",
    "Marshall Islands": "🇲🇭",
    "Martinique": "🇲🇶",
    "Mauritania": "🇲🇷",
    "Mauritius": "🇲🇺",
    "Mayotte": "🇾🇹",
    "Mexico": "🇲🇽",
    "Micronesia, Federated States of Micronesia": "🇫🇲",
    "Moldova, Republic of Moldova": "🇲🇩",
    "Monaco": "🇲🇨",
    "Mongolia": "🇲🇳",
    "Montenegro": "🇲🇪",
    "Montserrat": "🇲🇸",
    "Morocco": "🇲🇦",
    "Mozambique": "🇲🇿",
    "Myanmar": "🇲🇲",
    "Namibia": "🇳🇦",
    "Nauru": "🇳🇷",
    "Nepal": "🇳🇵",
    "Netherlands": "🇳🇱",
    "Netherlands Antilles": "🇳🇱",
    "New Caledonia": "🇳🇨",
    "New Zealand": "🇳🇿",
    "Nicaragua": "🇳🇮",
    "Niger": "🇳🇪",
    "Nigeria": "🇳🇬",
    "Niue": "🇳🇺",
    "Norfolk Island": "🇳🇫",
    "Northern Mariana Islands": "🇲🇵",
    "Norway": "🇳🇴",
    "Oman": "🇴🇲",
    "Pakistan": "🇵🇰",
    "Palau": "🇵🇼",
    "Palestinian Territory, Occupied": "🇵🇸",
    "Panama": "🇵🇦",
    "Papua New Guinea": "🇵🇬",
    "Paraguay": "🇵🇾",
    "Peru": "🇵🇪",
    "Philippines": "🇵🇭",
    "Pitcairn": "🇵🇳",
    "Poland": "🇵🇱",
    "Portugal": "🇵🇹",
    "Puerto Rico": "🇵🇷",
    "Qatar": "🇶🇦",
    "Reunion": "🇷🇪",
    "Romania": "🇷🇴",
    "Russia": "🇷🇺",
    "Rwanda": "🇷🇼",
    "Saint Barthelemy": "🇧🇱",
    "Saint Helena": "🇸🇭",
    "Saint Kitts and Nevis": "🇰🇳",
    "Saint Lucia": "🇱🇨",
    "Saint Martin": "🇲🇫",
    "Saint Pierre and Miquelon": "🇵🇲",
    "Saint Vincent and the Grenadines": "🇻🇨",
    "Samoa": "🇼🇸",
    "San Marino": "🇸🇲",
    "Sao Tome and Principe": "🇸🇹",
    "Saudi Arabia": "🇸🇦",
    "Senegal": "🇸🇳",
    "Serbia": "🇷🇸",
    "Seychelles": "🇸🇨",
    "Sierra Leone": "🇸🇱",
    "Singapore": "🇸🇬",
    "Slovakia": "🇸🇰",
    "Slovenia": "🇸🇮",
    "Solomon Islands": "🇸🇧",
    "Somalia": "🇸🇴",
    "South Africa": "🇿🇦",
    "South Georgia and the South Sandwich Islands": "🇬🇸",
    "South Sudan": "🇸🇸",
    "Spain": "🇪🇸",
    "Sri Lanka": "🇱🇰",
    "Sudan": "🇸🇩",
    "Suriname": "🇸🇷",
    "Svalbard and Jan Mayen": "🇸🇯",
    "Swaziland": "🇸🇿",
    "Sweden": "🇸🇪",
    "Switzerland": "🇨🇭",
    "Syrian Arab Republic": "🇸🇾",
    "Taiwan": "🇹🇼",
    "Tajikistan": "🇹🇯",
    "Tanzania, United Republic of Tanzania": "🇹🇿",
    "Thailand": "🇹🇭",
    "Timor-Leste": "🇹🇱",
    "Togo": "🇹🇬",
    "Tokelau": "🇹🇰",
    "Tonga": "🇹🇴",
    "Trinidad and Tobago": "🇹🇹",
    "Tunisia": "🇹🇳",
    "Turkey": "🇹🇷",
    "Turkmenistan": "🇹🇲",
    "Turks and Caicos Islands": "🇹🇨",
    "Tuvalu": "🇹🇻",
    "Uganda": "🇺🇬",
    "Ukraine": "🇺🇦",
    "United Arab Emirates": "🇦🇪",
    "United Kingdom": "🇬🇧",
    "United States": "🇺🇸",
    "United States Minor Outlying Islands": "🇺🇲",
    "Uruguay": "🇺🇾",
    "Uzbekistan": "🇺🇿",
    "Vanuatu": "🇻🇺",
    "Venezuela": "🇻🇪",
    "Vietnam": "🇻🇳",
    "Virgin Islands, British": "🇻🇬",
    "Virgin Islands, U.S.": "🇻🇮",
    "Wallis and Futuna": "🇼🇫",
    "Western Sahara": "🇪🇭",
    "Yemen": "🇾🇪",
    "Zambia": "🇿🇲",
    "Zimbabwe": "🇿🇼"
}

export const LanguagesList = [
    {label: "Afrikaans", value: "af"},
    {label: "Albanian", value: "sq"},
    {label: "Amharic", value: "am"},
    {label: "Arabic", value: "ar"},
    {label: "Aragonese", value: "an"},
    {label: "Armenian", value: "hy"},
    {label: "Asturian", value: "ast"},
    {label: "Azerbaijani", value: "az"},
    {label: "Basque", value: "eu"},
    {label: "Belarusian", value: "be"},
    {label: "Bengali", value: "bn"},
    {label: "Bosnian", value: "bs"},
    {label: "Breton", value: "br"},
    {label: "Bulgarian", value: "bg"},
    {label: "Catalan", value: "ca"},
    {label: "Central Kurdish", value: "ckb"},
    {label: "Chinese", value: "zh"},
    {label: "Chinese (Hong Kong)", value: "zh-HK"},
    {label: "Chinese (Simplified)", value: "zh-CN"},
    {label: "Chinese (Traditional)", value: "zh-TW"},
    {label: "Corsican", value: "co"},
    {label: "Croatian", value: "hr"},
    {label: "Czech", value: "cs"},
    {label: "Danish", value: "da"},
    {label: "Dutch", value: "nl"},
    {label: "English", value: "en"},
    {label: "English (Australia)", value: "en-AU"},
    {label: "English (Canada)", value: "en-CA"},
    {label: "English (India)", value: "en-IN"},
    {label: "English (New Zealand)", value: "en-NZ"},
    {label: "English (South Africa)", value: "en-ZA"},
    {label: "English (United Kingdom)", value: "en-GB"},
    {label: "English (United States)", value: "en-US"},
    {label: "Esperanto", value: "eo"},
    {label: "Estonian", value: "et"},
    {label: "Faroese", value: "fo"},
    {label: "Filipino", value: "fil"},
    {label: "Finnish", value: "fi"},
    {label: "French", value: "fr"},
    {label: "French (Canada)", value: "fr-CA"},
    {label: "French (France)", value: "fr-FR"},
    {label: "French (Switzerland)", value: "fr-CH"},
    {label: "Galician", value: "gl"},
    {label: "Georgian", value: "ka"},
    {label: "German", value: "de"},
    {label: "German (Austria)", value: "de-AT"},
    {label: "German (Germany)", value: "de-DE"},
    {label: "German (Liechtenstein)", value: "de-LI"},
    {label: "German (Switzerland)", value: "de-CH"},
    {label: "Greek", value: "el"},
    {label: "Guarani", value: "gn"},
    {label: "Gujarati", value: "gu"},
    {label: "Hausa", value: "ha"},
    {label: "Hawaiian", value: "haw"},
    {label: "Hebrew", value: "he"},
    {label: "Hindi", value: "hi"},
    {label: "Hungarian", value: "hu"},
    {label: "Icelandic", value: "is"},
    {label: "Indonesian", value: "id"},
    {label: "Interlingua", value: "ia"},
    {label: "Irish", value: "ga"},
    {label: "Italian", value: "it"},
    {label: "Italian (Italy)", value: "it-IT"},
    {label: "Italian (Switzerland)", value: "it-CH"},
    {label: "Japanese", value: "ja"},
    {label: "Kannada", value: "kn"},
    {label: "Kazakh", value: "kk"},
    {label: "Khmer", value: "km"},
    {label: "Korean", value: "ko"},
    {label: "Kurdish", value: "ku"},
    {label: "Kyrgyz", value: "ky"},
    {label: "Lao", value: "lo"},
    {label: "Latin", value: "la"},
    {label: "Latvian", value: "lv"},
    {label: "Lingala", value: "ln"},
    {label: "Lithuanian", value: "lt"},
    {label: "Macedonian", value: "mk"},
    {label: "Malay", value: "ms"},
    {label: "Malayalam", value: "ml"},
    {label: "Maltese", value: "mt"},
    {label: "Marathi", value: "mr"},
    {label: "Mongolian", value: "mn"},
    {label: "Nepali", value: "ne"},
    {label: "Norwegian", value: "no"},
    {label: "Norwegian Bokmål", value: "nb"},
    {label: "Norwegian Nynorsk", value: "nn"},
    {label: "Occitan", value: "oc"},
    {label: "Oriya", value: "or"},
    {label: "Oromo", value: "om"},
    {label: "Pashto", value: "ps"},
    {label: "Persian", value: "fa"},
    {label: "Polish", value: "pl"},
    {label: "Portuguese", value: "pt"},
    {label: "Portuguese (Brazil)", value: "pt-BR"},
    {label: "Portuguese (Portugal)", value: "pt-PT"},
    {label: "Punjabi", value: "pa"},
    {label: "Quechua", value: "qu"},
    {label: "Romanian", value: "ro"},
    {label: "Romanian (Moldova)", value: "mo"},
    {label: "Romansh", value: "rm"},
    {label: "Russian", value: "ru"},
    {label: "Scottish Gaelic", value: "gd"},
    {label: "Serbian", value: "sr"},
    {label: "Serbo", value: "sh"},
    {label: "Shona", value: "sn"},
    {label: "Sindhi", value: "sd"},
    {label: "Sinhala", value: "si"},
    {label: "Slovak", value: "sk"},
    {label: "Slovenian", value: "sl"},
    {label: "Somali", value: "so"},
    {label: "Southern Sotho", value: "st"},
    {label: "Spanish", value: "es"},
    {label: "Spanish (Argentina)", value: "es-AR"},
    {label: "Spanish (Latin America)", value: "es-419"},
    {label: "Spanish (Mexico)", value: "es-MX"},
    {label: "Spanish (Spain)", value: "es-ES"},
    {label: "Spanish (United States)", value: "es-US"},
    {label: "Sundanese", value: "su"},
    {label: "Swahili", value: "sw"},
    {label: "Swedish", value: "sv"},
    {label: "Tajik", value: "tg"},
    {label: "Tamil", value: "ta"},
    {label: "Tatar", value: "tt"},
    {label: "Telugu", value: "te"},
    {label: "Thai", value: "th"},
    {label: "Tigrinya", value: "ti"},
    {label: "Tongan", value: "to"},
    {label: "Turkish", value: "tr"},
    {label: "Turkmen", value: "tk"},
    {label: "Twi", value: "tw"},
    {label: "Ukrainian", value: "uk"},
    {label: "Urdu", value: "ur"},
    {label: "Uyghur", value: "ug"},
    {label: "Uzbek", value: "uz"},
    {label: "Vietnamese", value: "vi"},
    {label: "Walloon", value: "wa"},
    {label: "Welsh", value: "cy"},
    {label: "Western Frisian", value: "fy"},
    {label: "Xhosa", value: "xh"},
    {label: "Yiddish", value: "yi"},
    {label: "Yoruba", value: "yo"},
    {label: "Zulu", value: "zu"}
];


export const TopicCategories = [
    {
      category: "Fun and Interesting",
      topics: [
        "Unusual Animal Friendships",
        "Weirdest Food Combinations You've Tried",
        "Time Travel: Where and When Would You Go?",
        "Superpowers: What Would You Choose?",
      ],
    },
    {
      category: "Entertainment",
      topics: [
        "Favorite Movie Quotes of All Time",
        "Your Dream Celebrity Dinner Party",
        "Best Video Games of the Decade",
      ],
    },
    {
      category: "Travel and Adventure",
      topics: [
        "Bucket List Destinations",
        "Craziest Travel Stories",
        "If You Could Live Anywhere, Where Would It Be?",
      ],
    },
    {
      category: "Food and Cuisine",
      topics: [
        "DIY Pizza Toppings: What's Your Secret?",
        "Strangest Food You've Tried While Traveling",
        "Foodie Adventures: Local Eats",
      ],
    },
  ];
  

