import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProviders } from './theme.provider'
import AuthContext from '@/context/AuthContext'
import ToasterContext from '@/context/ToasterContext'
import SpacesSocketProvider from '@/contexts/SpacesSocketContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sparktalk',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={`dark:bg-[#121212] ${inter.className}`}>
        <AuthContext>
          <ThemeProviders>
            <ToasterContext />
            <SpacesSocketProvider>
              {/* <ActiveStatus /> */}
            {children}
            </SpacesSocketProvider>
          </ThemeProviders>
        </AuthContext>
      </body>
    </html >
  )
}
